### ISSUE TITLE
0531批次假阳性突变及命名错误情况

### ISSUE THREAD

**Issue by miranda92** [topgen-co-ltd/DiscussionBoard#10]
0531_1批次发现假阳性突变如下：
![image](https://user-images.githubusercontent.com/50906773/58787535-9647b980-861c-11e9-94e8-35a1bee7a483.png)
认为假阳性原因：1.NGS190529-18 bam文件显示两个方向reads数不均衡，且同批次其他样本该位置同样存在该情况，故认为该突变为假阳性
![image](https://user-images.githubusercontent.com/50906773/58787192-db1f2080-861b-11e9-98a9-837218de2fbd.png)
2.NGS190529-7 bam文件中该突变位置仅看到一条reads，故认为该突变为假阳性
![image](https://user-images.githubusercontent.com/50906773/58787508-84661680-861c-11e9-9079-3dc5be4a66c8.png)

0531_2批次中发现命名错误情况如下：
![image](https://user-images.githubusercontent.com/50906773/58790326-c2fecf80-8622-11e9-89c3-2cd7ad64e185.png)
此变异bam文件中显示如下：
![image](https://user-images.githubusercontent.com/50906773/58790358-d27e1880-8622-11e9-9b6a-a2441f2f8334.png)
此类问题一直存在，是否有办法解决？

**Comment by neversay4ever** [comment]
两个方向的reads不均衡，有可能是数据过滤时将一端reads过滤掉了，这个可以通过只保留pair reads，不用single read作比对来鉴别。

**Comment by neversay4ever** [comment]
仅看到一条read的，通过samtools筛选bam文件确认。如果真实一条read，意味着流程的过滤程序存在bug。

**Comment by neversay4ever** [comment]
命名错误是annovar的命名规则引起。以后可以测试下VEP注释。但是注释软件的结果经常有差异，在于同样的情况可以有多种命名方式，源于生物里概念的定义不完备，存在交集和遗漏的定义。

**Comment by neversay4ever** [comment]
以上由 @shishanfu 执行反馈。

**Comment by shishanfu** [comment]
1. NGS190529-18是VD肺癌核心板panel，建库方法是PCR，本身是不是就存在reads的不平衡性？
2. NGS90529-7样本的这个突变samtools统计一共两条reads，但是因为这个点是白名单call出来的，，我们是不经过reads数的处理的，如果需要加入reads数的筛选，请给我标准，我加入流程中，谢谢！
3. 我们的流程中已经引入爬虫修改突变命名，是否还存在错误？
