### ISSUE TITLE
oncoKB假阴性突变问题

### ISSUE THREAD

**Issue by shishanfu** [topgen-co-ltd/DiscussionBoard#11]
目前NGS190526-13DF样本发现一个oncoKB假阴性的突变，问题已解决，造成假阴性的原因如下：
* 流程分析结果经过`annovar`注释以后突变为：`EGFR:NM_005228:exon18:c.2127_2129del:p.709_710del`，而`oncoKB`数据库位点信息为：`EGFR:NM_005228:\S+E709_T710delinsD`
* `annovar`的注释结果与oncoKB不能完全匹配，所以才会出现oncoKB假阴性的情况，目前已经修改oncoKB数据库信息，可以匹配结果。

**Comment by Eloimsama** [comment]
NGS190526-13DF样本：EGFR:NM_005228:exon18:c.2127_2129del:p.Glu709_Thr710delinsAsp是报出来的真阳性，我们的数据库里有明确的批准药物，但是没有关联到190531_merge_target表格里。
