### ISSUE TITLE
strelka2和gatk4对比

### ISSUE THREAD

**Issue by asmlgkj** [topgen-co-ltd/DiscussionBoard#14]
Strelka2和gatk报出的结果差异比较大，strelka很快，由c++编写，大概是gatk的45倍，但是对于突变筛选不够严谨，比如爆出来存在reads最后的一个碱基，且reads整齐划一

共测试2个样本，一个突变交集为空，一个交集为0.

**Comment by Topgen-admin** [comment]
交集为空 和 交集为0 有什么区别？
