### ISSUE TITLE
实验室质评2017，2018 三批组织FFPE样本的结果

### ISSUE THREAD

**Issue by asmlgkj** [topgen-co-ltd/DiscussionBoard#15]
本次评估是为了测试我们目前流程的结果和实验室质评关于肿瘤组织体细胞突变的可靠性。

整体来看，经过流程得到的突变的可靠性还是非常高，直接用GATK的结果和答案差别比较大，所以直接的gatk的结果假阳性比较大，流程通过筛选能精准的找到28个(答案一共12+10+9=31个突变)中应该报出来的突变

三批次样品，都是按照非配对FFPE分析的流程分析，

在人工排除共同的突变之后以及我们panel不包括的基因之后，每一批大概都有2个共同的突变，需要人工去除

第一批：   总共6个样本，2个样本都缺少KRAS突变，强制calling才得到这些突变，也是failed的，但是在igv中看到的不一致，igv有reads支持
![image](https://user-images.githubusercontent.com/50854682/59002545-629ba800-8845-11e9-9b53-49a09efcf78f.png)
![image](https://user-images.githubusercontent.com/50854682/59002559-6a5b4c80-8845-11e9-8223-74b9182e406d.png)
![image](https://user-images.githubusercontent.com/50854682/59002568-70512d80-8845-11e9-9da9-e7de1a8c3f3e.png)
![image](https://user-images.githubusercontent.com/50854682/59002571-7515e180-8845-11e9-9c32-442f42ebfa41.png)

6个样本共12个突变，少报了 2个同样的突变，深度是三四百

第二批：6个样本，一共9个突变，有2个样本多报了GNAQ这个突变，突变频率7%左右

第三批 ： 6个样本，一共10个突变， 有一个样本中PIK3CA在vcf是PASS，没报，突变频率是6%(85,5)，应该是support alt的reads 数目不够。

**Comment by neversay4ever** [comment]
这件任务的背景描述一下

**Comment by asmlgkj** [comment]
@neversay4ever 已经修改

**Comment by cai2002cai** [comment]
如何改进？

**Comment by shishanfu** [comment]
结果的文件在哪里？我去看看PIK3CA这个突变被过滤掉的原因，谢谢！
