### ISSUE TITLE
Bpipe 流程控制软件

### ISSUE THREAD

**Issue by ZKai0801** [topgen-co-ltd/DiscussionBoard#19]
昨天试着用了一下，确实能够实现并行的效果，并且它对日志的输出等都有很好的管理，确实是一个不错的软件
但是这套系统它自称是一门语言，也就是意味着里面很多规则是需要时间去学习的，比如最基础的一些if判断之类的，所以把整个流程串起来还是需要一定时间的。

我这周看看吧，如果时间充裕就把这弄好

**Comment by ZKai0801** [comment]
# bpipe 测试

本次测试中出现了很多意想不到的bug，加上本身测试的周期比较长，因此耗时超乎了预期



我先说明一下bpipe串成的流程样式：

trim_ends + align +
[fusion, sam2bam + markdup +
[gatk, mutect2] +
[cna + theta, msi, [anno_germline, anno_somatic, anno_hotspot] +
mv_anno + [clinics, tmb, qc] + hla]]

> bpipe使用的是groovy的语法，
>
> 加号表示的是串联;
> 逗号表示的是并联;
>
> [ ] 相当于list，里面的元素需要逗号进行分隔
>
> 剩余语法请参考 [bpipe官方文档](https://github.com/ssadedin/bpipe/tree/master/docs)

用语言来形容一下，就是先去接头再比对（这两步中的软件均能实现多线程），比对完成开始并行 fusion 和 sam2bam + markduplicate + gatk + mutect2的并行， 巧的是，从 sam2bam、markduplicate 到 gatk/mutect2的前几步均无法实现多线程，而fusion这一步恰好资源占用率高、占用时间长，刚好完美的错开，保证了总线程数的一致，并且gatk的HaplotypeCaller这一步往往会在mutect2的calling之前完成，也能正好错开（这两步同样也是资源消耗最大、支持多线程的步骤）。之后的几步资源消耗相对较少，基本可以实现全部并行（有依赖除外）

因此可以说，这样的连接，是目前流程运行最高效的方式



---



## 对比测试

测试对比了**单个样本**运行速度以及**多个样本**并行的速度，

为避免其他人任务的影响，本次测试只在服务器空闲时期进行



#### 单样本流程测试

目标： 证明bpipe流程相对shell流程确实有提升

测试在**32**上完成，该机器共20核，测试中所有软件的线程数均调为**8**

|     样本ID     | 文件大小  |  shell 流程   |  bpipe 流程   |
| :------------: | :-------: | :-----------: | :-----------: |
| NGS190605-16DW | 195M/200M |    33分7秒    |   17分32秒    |
| NGS190605-2DU  | 2.3G/2.4G | 8小时19分37秒 | 6小时40分38秒 |
| NGS190605-6DE  | 797M/876M | 1小时36分20秒 | 1小时2分17秒  |
| NGS190606-14DA | 130M/135M |    19分6秒    |   14分28秒    |
| NGS190606-26CF | 339M/347M |   59分12秒    |   34分41秒    |
| NGS190606-32CC | 324M/333M |   53分27秒    |   32分25秒    |
| NGS190606-4DR  | 316M/325M |    55分5秒    |   16分32秒    |
| NGS190606-8DJ  | 165M/169M |    24分2秒    |   12分37秒    |
| NGS190606-9DF  | 112M/115M |   21分21秒    |   12分37秒    |
| NGS190608-42DP |  50M/51M  |    7分48秒    |    4分58秒    |
| NGS190610-12VD |  12M/12M  |    5分15秒    |    2分57秒    |



#### 多样本流程测试

1. 速度测试

目标：

1） 测试实际运行中，bpipe流程在批量的情况下也对流程速度有所提升

2）线程数过多，会引起阻塞现象，严重者可能拖慢运行速度

测试在**32**上完成

| 批次 | 样本数量 |         并行数量         | shell 流程耗时 | bpipe 流程耗时 |
| :------: | :-----------: | :-----------: | :------: | :------: |
| 190612-1 |    40    |            5             | 3小时21分27秒 | 2小时32分11秒 |
| 190612-2 |    22    |            5             | 3小时1分22秒 | 2小时9分49秒 |
| 190612-3 | 4 | 5 | 3小时29分13秒 | 2小时26分15秒 |
| 190612-1 | 40 | 10（现流程的默认并行数） | 3小时5分30秒 | 2小时49分30秒 |



2. 探寻最优解

目标：

理论上，当机器的所有内核都能被同时调用时运行速度最快，但由于软件的性能表现关系，往往设定的时候稍微设高一点的线程速度会更快，但如果设置的太高，又会造成堵塞

因此本次实验意在探寻并行数量为多少时，运行效率最高

本测试在**118**上完成;

118共24核，若线程数设为8，则理论上同时运行3个样本时，cpu会达到饱和

|   批次   | 线程数 | 并行数 | shell 流程耗时 | bpipe 流程耗时 |
| :------: | :----: | :----: | :------------: | :------------: |
| 190621-1 |   8    |   2    | 7小时24分15秒  | 4小时25分50秒  |
| 190621-1 |   8    |   3    | 5小时11分52秒  |  3小时9分18秒  |
| 190621-1 |   8    |   4    |  3小时59分1秒  |  2小时27分9秒  |
| 190621-1 |   8    |   5    | 3小时26分33秒  | 2小时13分19秒  |





## 测试总结

Bpipe确实对运行速度有一定程度的提升。单个样本的大小、样本的panel类型，以及样本并行的数量均对提升的空间有所影响，单样本测试很好的说明了这点

同样，在第一组的多样本测试中，Bpipe对比原本的shell的流程，无论是核心版批次还是大panel批次，运行速度均有不小的提升。但值得注意的是，当样本并行数调为10之后，bpipe流程不出所料运行速度有所降低，但shell流程运行速度反而有所提升。而在shell流程的运行过程中，32这台服务器还是出现了明显的卡顿，这意味着shell流程在运行过程中，过多的步骤只能调用单线程运算，因此即使cpu出现拥堵，运行时间还是有所缩短; 不过即使如此，shell流程的耗时时间依旧长于bpipe流程。

第二组的多样本测试旨在探寻118中并行数的最优解，与预期相同的是，并行数设为3，线程数设为8的时候，流程耗时并非最短，服务器中的大量时间还是被浪费掉了; 而意料之外的是，并行数为5的时候，流程运行时间还是比并行数为4的时候短，虽然差距不多，但确确实实从一定方面反应出了各软件直接对线程的利用率差距巨大。由于时间关系，测试并没有继续将并行数调高，但基本可以肯定的是，在并行数为4和5左右，服务器的利用率最高，再高就会出现拥堵的情况。

当然除了运行速度的提升之外，Bpipe的使用能让我们对流程有着更全面的调控，比如我们如果只需要重新跑部分的流程（Bpipe中称为一个stage），原流程中就需要我们重新建立一个该部分的流程样本，再生成出相应样本的具体流程，最后才能运行; 或者注释掉其余部分的流程再运行。但使用Bpipe便可以直接运行该部分，

例如：

`bpipe execute -s test.pipe 'cna'`

另外，Bpipe有着自己一套完整的日志体制，在运行了Bpipe的文件夹中（对我们来说，即单个样本的文件夹），可以很方便的查看 历史命令/输出信息/历史记录 等。

见 `commandlog.txt` 、`bpipe logs` 等



当然Bpipe也有着自己的一些劣势：

其一，在Bpipe的串联的流程中，后续的流程对前面的流程有着依赖关系，意味着如果前面流程报错，则后续流程无法正常进行，我们的流程在运行的过程中难免会遇到一些很小很小的问题，这些问题往往不会对结果产生任何影响，但当Bpipe接受到这个错误信号的时候，它就会直接终止流程; 

其二，学习Bpipe语言需要一定的时间成本，虽然我已经使用最最基础的方式来构建了Bpipe流程，但是大家还是需要学习一下Bpipe的语法，否则在构建出新流程的时候可能会遇到一些困难



Bpipe 现已在workflow中包装好，可用 `-c bpipe`进行调用，之后如果大家评测没有问题，即可将其设为默认

**Comment by neversay4ever** [comment]
开天展示出高级工程师的素质，：）

**Comment by ZKai0801** [comment]
哪里哪里，这还要感谢各位领导们的悉心教导以及同事们的互相支持 (つд⊂)ｴｰﾝ

**Comment by Topgen-admin** [comment]
现生产流程已按bpipe正常运作，暂时没有太大问题，之后若有问题可以重开此issue
