### ISSUE TITLE
东方肝胆医院一例泛癌种样本结果（TMB）被质疑

### ISSUE THREAD

**Issue by cxxie** [topgen-co-ltd/DiscussionBoard#20]
东方肝胆医院一例泛癌种检测FFPE组织样本（NGS190424-4）在我室检测TMB结果为低，销售反馈该患者2018年10月在其它地方（允英医学检验所）针对免疫治疗的检测结果为高，与我室结果差异太大，提出质疑。
我们查找了该样本原始数据，去重后有效平均深度749，覆盖率99.34%，均一性良好（96.82%>0.2*平均深度)，数据质量合格，且所报突变位点均人工核对过，没有问题。
然后我们比对了对方公司检出的免疫相关或意义未明突变，情况如下：
1） 8个突变中，除了TP53 突变跟我们报的点是一样的（转录本不一样，所以描述有差异，但频率相差极大，我室47.98%，对方91%），其它的6个突变在我们的VCF中没有报，原始结果里也确实没有看到，
2）8个突变中，其中PMS2 c.706-3C>A位点位于polyT旁边，我们该批次样本均存在类似频率的变异（该批次样本均有，位于poly序列区，且只出现在单向reads），分析流程直接就过滤掉了，没有报，人工核查也判定为假阳性
   所以，单从数据上来看，我们至少可以确定，我们的分析并没有漏报，从数据质量看，对于7-20%频率这么高的突变，漏检的可能性也很低，然如果是由于样本差异，导致检测结果单位点突变差异这么大，那在TMB数值上有明显差异，也是很有可能的。
   总而言之，从我们的样本结果质量和分析流程来看，我们的结果是可信的。
附：
对方结果
PMS2 (19%)（exon8,c.706-3C>A）；
POLD1(14%)（exon6,c.631C>A, p.R211S）；
POLE(13%)（exon22,c.2498G>A,p.G833D）；
TP53(91%)（exon4,c.428G>T,p.C143F）；
NOTCH1(15%)（exon34,c.6289C>A,p.P2097T）；
ALK(10%)（exon14,c.2389G>A,p.E797K）；
KDR(7%)（exon23,c.3075C>G,p.I1025M）；
 ABL1(7%)（exon11,c.2861G>T,p.G954V）

**Comment by Topgen-admin** [comment]
太感动了，我要把这置顶一段时间让大家都看看
顺便问一下，我们跟他们是同一个panel吧？

**Comment by neversay4ever** [comment]
补充一下判断逻辑：由于两次结果原始样本差异较大（样本类型、取样时间），必须先根据germline的结果（如化疗部分）确定一些基础结果的共识是一致的。

**Comment by cxxie** [comment]
补充一下，比对过化疗相关SNP位点，10个同样的位点结果是一致的；
另一家公司的panel跟我们的肯定是不一样的，但是很多基因应该是一样的，至少对方报出来的8个突变位置，都在我们的panel的检测范围内。
