### ISSUE TITLE
报告可视化工作需求

### ISSUE THREAD

**Issue by hehs-pm** [topgen-co-ltd/DiscussionBoard#27]
刘帅提出BRCA检测报告需要做类似的展示（安诺优达报告）
![image](https://user-images.githubusercontent.com/51812893/59735882-0778a500-928a-11e9-89be-e3c71218f1a5.png)
1、我们是否能够做类似的，或以前展示的横版的？

如果可以，做出来的图如果手工添加，又增加了新的工作量和难度，所以还需要

2、设置一种自动化报告模式，参照之前做简版报告的方式

请生信部门协助

**Comment by Topgen-admin** [comment]
这个我们昨天讨论过，目前实在没有人手来做这件事情，如果真的要做，请等两个月左右的时间
