### ISSUE TITLE
118服务器运算速度显著降低

### ISSUE THREAD

**Issue by ZKai0801** [topgen-co-ltd/DiscussionBoard#28]
这段时间注意到118服务器运算速度显著降低，经过一段时间的观察，发现是gatk无法调用多线程的关系，导致运算时间成倍的增长。
我们使用了同样的数据，同样的任务提交方式，分别在32和118上进行了测试，发现32上可以调用多线程，而118无论如何就是无法调用多线程。而其余的软件例如**genefuse**则可以正常使用。

对于问题出现的原因，我们目前实在没有头绪，只能说大致的排除了 `os.system` 与 `subprocess` 之间差异的问题。这个问题急需解决，否则会严重影响到出报告的时间

**Comment by neversay4ever** [comment]
@龚鑫源118和32机器配置不一样吗？最简单粗暴的方法是把32拿到湖州，然后把118拿回来。

**Comment by shishanfu** [comment]
GATK使用多线程的时候，会调用gcc包里的GOMP模块，但是118和32服务器gcc模块安装方式不同，导致118上面GATK分配多线程是调用失败，只能利用到一个线程去处理数据。目前通过更新118服务器gcc模块已经修复问题，但是我们为程序提供的线程数并不能满负荷利用，比如定义8线程，程序执行的时候不是所有的时间都是按照8线程执行，CPU的利用率一直在上下浮动，不稳定，后期需解决这个问题。

**Comment by ZKai0801** [comment]
不得不说龚鑫确实厉害，能在如此短的时间内确定问题源头。。。不转生信太可惜了
关于CPU利用率浮动的问题是gatk需要处理的，感觉不是我们能解决的，有个比较好的方法是设置高于机器本身的线程数，在排队等候的任务不是过多的情况下，这种方法可以加快运行速度

这个issue已成功解决，撒花～
