### ISSUE TITLE
整理560_gene_NM_ref.txt的错误

### ISSUE THREAD

**Issue by asmlgkj** [topgen-co-ltd/DiscussionBoard#29]
之前那个560文件里面的问题 
1：基因存在在refgene找不到的，
2 不同基因错误的对应到同一个转录本， 
3 对应的转录本是ensemble编号，没有转成NM编号，
4 对应的NM编号在refgene找不到，改成最长的那个可以找到的

**Comment by Topgen-admin** [comment]
good job!
