### ISSUE TITLE
流程中爬虫爬取速度过慢

### ISSUE THREAD

**Issue by ZKai0801** [topgen-co-ltd/DiscussionBoard#7]
刚刚跟史大哥提及了这个问题，而造成爬虫速度低下的原因是湖州网速问题，同样的文件，在32上跑可能一分钟不到; 而在118上跑，如果网络中断，脚本不断重试，运行半个小时甚至数个小时都有可能。

跟龚鑫交流了一下，湖州网速慢的问题是因为 118 这台机器网络是途经上海这边的，如果我们能用另外一台机器做跳转，以此保持与上海的连接，理论上会加速118本身的网速，但实际情况需要测试。

但鉴于湖州目前就一台空闲的电脑，如果用作跳转，我们就无法用它做备用。。。

@cai2002cai @neversay4ever 
麻烦严博蔡总几位高管商量下，看看这问题能如何解决。。

**Comment by Topgen-admin** [comment]
现在我们会先测试一下用其他机器跳转的速度 @optimism1207 
麻烦龚鑫测试完告知我们一下，然后看看对于上海报告组这边影响多大。如果影响不大，便可以申请买个新的机器，便宜点就行_

**Comment by optimism1207** [comment]
已经改成中转的方式了，暂时用的那台闲置的服务器

刚测试网络状况算是比较好，从242 ping100次延迟平均增加了0.5ms，带宽影响也很小(基于有线网络)，坏的情况下现在不好测试，至于对爬虫脚本有没有改善，这个需要@ZKai0801他们测试了，报告那边也要另外测试一段时间看下实际使用情况

### 100次ping测试

    --- 192.168.10.111 ping statistics ---
    100 packets transmitted, 100 received, 0% packet loss, time 99135ms
    rtt min/avg/max/mdev = 16.784/18.588/19.459/0.450 ms

    --- 192.168.10.118 ping statistics ---
    100 packets transmitted, 100 received, 0% packet loss, time 99137ms
    rtt min/avg/max/mdev = 17.047/19.089/22.496/0.680 ms

### iperf3 60秒带宽测试

    111--->242
    
    [ ID]   Interval          Transfer    Bandwidth       Retr
    [SUM]   0.00-60.00  sec   386 MBytes  54.0 Mbits/sec  600   sender
    [SUM]   0.00-60.00  sec   380 MBytes  53.2 Mbits/sec        receiver
   
    118--->242

    [ ID]   Interval          Transfer    Bandwidth       Retr
    [SUM]   0.00-60.00  sec   384 MBytes  53.7 Mbits/sec  584   sender
    [SUM]   0.00-60.00  sec   380 MBytes  53.1 Mbits/sec        receiver

**Comment by ZKai0801** [comment]
给你手动点赞
我刚刚将爬虫部分加了时间记录，具体效果怎么样还是要等多跑几批数据再说，毕竟网络时好时坏，一次的数据并不能说明什么。
关于延迟问题的话，我们现在开始实用裁剪后的bam文件，相信这部分的时间可以被抵消掉一部分

@Eloimsama 麻烦周一的时候告知一声具体的速度情况，如果能接受的话我们就可以采用这种方案了：）

**Comment by optimism1207** [comment]
便宜点的话服务器/小型工作站我就不看了，基本5000起步，选普通商用台式，那台做跳转的机器选了如下这几台，具体选哪台可以根据预算和之后是否会有其它用途来（ ps:  如果选最后一个的话，因性能较好，比较浪费，可以替换公司现有的一台台式，将换下的用作跳转机器 ）

1000档位
攀升 Intel J3160（四核） 8G内存 120GSSD 三年上门
https://item.jd.com/100005092794.html
售价: 999
优点: 较便宜，功耗低，热设计功耗 6W
缺点: 性能弱，以后不做跳转用了，就没用了，用作办公会很卡

2000档位
戴尔 成就3470 奔腾G5400 （双核四线程） 4G 1T 四年上门售后
https://item.jd.com/7237194.html
售价: 1999
优点: 价格中等，CPU性能比第一个强很多，略弱于i3 6100，跟公司现在用的i3台式机差不多，多一年售后
缺点: 内存较低，若之后用作普通办公需要加内存

3000档位
联想 天逸510S i3-9100（四核四线程）8G 1T 三年上门
https://item.jd.com/100005626636.html#crumb-wrap
售价: 2799
优点: 平台较新，性能较强，若之后用作普通办公完全足够
缺点: 售价相对较高

**Comment by Topgen-admin** [comment]
@neversay4ever 麻烦严博选一台，这个问题就解决了

**Comment by Topgen-admin** [comment]
上周龚鑫 @optimism1207 已经将爬虫所爬取的网站单独分开，测试到目前为止都没有出现过断网重连的信息，说明此法还是可行的，如果之后再有问题，再重开这个issue

最后，感谢龚鑫同学的努力，为公司省下一笔服务器的开销，大家掌声鼓励 ～～～
